### ISSUE TITLE
GUI TODOs

### ISSUE THREAD

**Issue by dorleitman** [sagioto/LipReading#1]
- Improve videoConfig color picker - not working right.
- VideoConfig - check threads run, running out of memory after a while.
- Takes a long time to load videoCongif panel - improve
- Make GUI more pretty (change buttons to images, add lips image in videoConfig, better explanations in videoConfig, Main logo, add progressbar or loading signs to lipReader & etc.)
- Arrange code
- Add training set panel
- Add better exception handles

**Comment by sagioto** [comment]
it's enhancements not bugs,

I don't understand what is abstract video extractor? and why do we need it?
also why another sticker extractor and nit use the class we already have?
it looks like the whole difference is just read the scalar values from another class and add a boolean to stop the extraction.

Am I missing something?

**Comment by dagansandler** [comment]
Enhancements or Bugs, we should break them down to different Issues, so they're more like individual stories and we can (maybe?) work on them independently.

The rest of the questions should also go to the respected classes they refer to :)

**Comment by dorleitman** [comment]
The first 3 are bugs... 

The old stickerExtractor captures video, opens a new Canvas, draws point. The new stickerExtractor, only gets an image & return its points. The UI now deals with capturing & drawing points.
Until the prototype in not done and can performs tests, I didnt want to touch anything that works. When we will be completely done with the prototype we will update the old vision classes. Its true that the 2 abstracts are similar, I had something that I needed to change in the new abstract and I didnt want to break/start changing the working classes we have so far.

**Comment by sagioto** [comment]
the current vision class only displays if isCI() is true, You could just change the predicate...
